servers:
  # kebab case
  ip-address: 192.168.0.2
  # ipAddress: 192.168.0.2
  port: 2233
  timeout: -1
  serverTimeout: 3
  dataSize: 10
datasource:
  driverClassName: com.mysql.jdbc.Driver456
  # octal
  password: 0123
beer:
  german: 2
