server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot
      username: root
      password: 123123
#  cache:
#    type: redis
#    redis:
#      use-key-prefix: true
#      cache-null-values: false
#      key-prefix: aa
#      time-to-live: 10

#redis---------
#  redis:
#    host: localhost
#    port: 6379

#ehcache config--------
#  cache:
#    type: ehcache
#    ehcache:
#      config: ehcache.xml

memcached:
  servers: localhost:11211
  poolSize: 10
  opTimeout: 3000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
