#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/springboot
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 123123
#      maximum-pool-size: 50

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot
#    username: root
#    password: 123123
#    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 80
spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456
      maximum-pool-size: 50
